[0;1;31m‚óè[0m gunicorn.service - Gunicorn instance to serve piaarlab
     Loaded: loaded (/etc/systemd/system/gunicorn.service; enabled; vendor preset: enabled)
     Active: [0;1;31mfailed[0m (Result: exit-code) since Sat 2025-01-11 06:25:58 UTC; 58s ago
    Process: 406312 ExecStart=/home/piaar_selling_gmail_com/piaarlab/venv/bin/gunicorn --workers 3 --timeout 600 --bind 127.0.0.1:8000 piaarlab.wsgi:application [0;1;31m(code=exited, status=1/FAILURE)[0m
   Main PID: 406312 (code=exited, status=1/FAILURE)

Jan 11 06:25:54 piaarlab-vm gunicorn[406312]: [2025-01-11 06:25:54 +0000] [406312] [ERROR] connection to ('127.0.0.1', 8000) failed: [Errno 98] Address already in use
Jan 11 06:25:55 piaarlab-vm gunicorn[406312]: [2025-01-11 06:25:55 +0000] [406312] [ERROR] Connection in use: ('127.0.0.1', 8000)
Jan 11 06:25:55 piaarlab-vm gunicorn[406312]: [2025-01-11 06:25:55 +0000] [406312] [ERROR] connection to ('127.0.0.1', 8000) failed: [Errno 98] Address already in use
Jan 11 06:25:56 piaarlab-vm gunicorn[406312]: [2025-01-11 06:25:56 +0000] [406312] [ERROR] Connection in use: ('127.0.0.1', 8000)
Jan 11 06:25:56 piaarlab-vm gunicorn[406312]: [2025-01-11 06:25:56 +0000] [406312] [ERROR] connection to ('127.0.0.1', 8000) failed: [Errno 98] Address already in use
Jan 11 06:25:57 piaarlab-vm gunicorn[406312]: [2025-01-11 06:25:57 +0000] [406312] [ERROR] Connection in use: ('127.0.0.1', 8000)
Jan 11 06:25:57 piaarlab-vm gunicorn[406312]: [2025-01-11 06:25:57 +0000] [406312] [ERROR] connection to ('127.0.0.1', 8000) failed: [Errno 98] Address already in use
Jan 11 06:25:58 piaarlab-vm gunicorn[406312]: [2025-01-11 06:25:58 +0000] [406312] [ERROR] Can't connect to ('127.0.0.1', 8000)
Jan 11 06:25:58 piaarlab-vm systemd[1]: [0;1;39m[0;1;31m[0;1;39mgunicorn.service: Main process exited, code=exited, status=1/FAILURE[0m
Jan 11 06:25:58 piaarlab-vm systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mgunicorn.service: Failed with result 'exit-code'.[0m
